// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/crypto_parser.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_proto_crypto_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *PriceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_proto_crypto_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *PriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RatioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatioRequest) Reset() {
	*x = RatioRequest{}
	mi := &file_proto_crypto_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatioRequest) ProtoMessage() {}

func (x *RatioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatioRequest.ProtoReflect.Descriptor instead.
func (*RatioRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_parser_proto_rawDescGZIP(), []int{2}
}

func (x *RatioRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RatioResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	BuyRatio       string                 `protobuf:"bytes,2,opt,name=buy_ratio,json=buyRatio,proto3" json:"buy_ratio,omitempty"`
	SellRatio      string                 `protobuf:"bytes,3,opt,name=sell_ratio,json=sellRatio,proto3" json:"sell_ratio,omitempty"`
	LongShortRatio string                 `protobuf:"bytes,4,opt,name=long_short_ratio,json=longShortRatio,proto3" json:"long_short_ratio,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RatioResponse) Reset() {
	*x = RatioResponse{}
	mi := &file_proto_crypto_parser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatioResponse) ProtoMessage() {}

func (x *RatioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_parser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatioResponse.ProtoReflect.Descriptor instead.
func (*RatioResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_parser_proto_rawDescGZIP(), []int{3}
}

func (x *RatioResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RatioResponse) GetBuyRatio() string {
	if x != nil {
		return x.BuyRatio
	}
	return ""
}

func (x *RatioResponse) GetSellRatio() string {
	if x != nil {
		return x.SellRatio
	}
	return ""
}

func (x *RatioResponse) GetLongShortRatio() string {
	if x != nil {
		return x.LongShortRatio
	}
	return ""
}

var File_proto_crypto_parser_proto protoreflect.FileDescriptor

const file_proto_crypto_parser_proto_rawDesc = "" +
	"\n" +
	"\x19proto/crypto_parser.proto\"\"\n" +
	"\fPriceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rPriceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\fRatioRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8f\x01\n" +
	"\rRatioResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tbuy_ratio\x18\x02 \x01(\tR\bbuyRatio\x12\x1d\n" +
	"\n" +
	"sell_ratio\x18\x03 \x01(\tR\tsellRatio\x12(\n" +
	"\x10long_short_ratio\x18\x04 \x01(\tR\x0elongShortRatio2h\n" +
	"\x06Crypto\x12.\n" +
	"\vCryptoPrice\x12\r.PriceRequest\x1a\x0e.PriceResponse\"\x00\x12.\n" +
	"\vCryptoRatio\x12\r.RatioRequest\x1a\x0e.RatioResponse\"\x00B-Z+/Users/bezenov_v/Desktop/CryptoParser/protob\x06proto3"

var (
	file_proto_crypto_parser_proto_rawDescOnce sync.Once
	file_proto_crypto_parser_proto_rawDescData []byte
)

func file_proto_crypto_parser_proto_rawDescGZIP() []byte {
	file_proto_crypto_parser_proto_rawDescOnce.Do(func() {
		file_proto_crypto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crypto_parser_proto_rawDesc), len(file_proto_crypto_parser_proto_rawDesc)))
	})
	return file_proto_crypto_parser_proto_rawDescData
}

var file_proto_crypto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_crypto_parser_proto_goTypes = []any{
	(*PriceRequest)(nil),  // 0: PriceRequest
	(*PriceResponse)(nil), // 1: PriceResponse
	(*RatioRequest)(nil),  // 2: RatioRequest
	(*RatioResponse)(nil), // 3: RatioResponse
}
var file_proto_crypto_parser_proto_depIdxs = []int32{
	0, // 0: Crypto.CryptoPrice:input_type -> PriceRequest
	2, // 1: Crypto.CryptoRatio:input_type -> RatioRequest
	1, // 2: Crypto.CryptoPrice:output_type -> PriceResponse
	3, // 3: Crypto.CryptoRatio:output_type -> RatioResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_crypto_parser_proto_init() }
func file_proto_crypto_parser_proto_init() {
	if File_proto_crypto_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crypto_parser_proto_rawDesc), len(file_proto_crypto_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crypto_parser_proto_goTypes,
		DependencyIndexes: file_proto_crypto_parser_proto_depIdxs,
		MessageInfos:      file_proto_crypto_parser_proto_msgTypes,
	}.Build()
	File_proto_crypto_parser_proto = out.File
	file_proto_crypto_parser_proto_goTypes = nil
	file_proto_crypto_parser_proto_depIdxs = nil
}
