// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/crypto_parser.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceRequest struct { //!!!
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_proto_crypto_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_crypto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *PriceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_proto_crypto_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crypto_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_crypto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *PriceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_crypto_parser_proto protoreflect.FileDescriptor

const file_proto_crypto_parser_proto_rawDesc = "" +
	"\n" +
	"\x19proto/crypto_parser.proto\"\"\n" +
	"\fPriceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rPriceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage28\n" +
	"\x06Crypto\x12.\n" +
	"\vCryptoPrice\x12\r.PriceRequest\x1a\x0e.PriceResponse\"\x00B-Z+/Users/bezenov_v/Desktop/CryptoParser/protob\x06proto3"

var (
	file_proto_crypto_parser_proto_rawDescOnce sync.Once
	file_proto_crypto_parser_proto_rawDescData []byte
)

func file_proto_crypto_parser_proto_rawDescGZIP() []byte {
	file_proto_crypto_parser_proto_rawDescOnce.Do(func() {
		file_proto_crypto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crypto_parser_proto_rawDesc), len(file_proto_crypto_parser_proto_rawDesc)))
	})
	return file_proto_crypto_parser_proto_rawDescData
}

var file_proto_crypto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_crypto_parser_proto_goTypes = []any{
	(*PriceRequest)(nil),  // 0: PriceRequest
	(*PriceResponse)(nil), // 1: PriceResponse
}
var file_proto_crypto_parser_proto_depIdxs = []int32{
	0, // 0: Crypto.CryptoPrice:input_type -> PriceRequest
	1, // 1: Crypto.CryptoPrice:output_type -> PriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_crypto_parser_proto_init() }
func file_proto_crypto_parser_proto_init() {
	if File_proto_crypto_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crypto_parser_proto_rawDesc), len(file_proto_crypto_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crypto_parser_proto_goTypes,
		DependencyIndexes: file_proto_crypto_parser_proto_depIdxs,
		MessageInfos:      file_proto_crypto_parser_proto_msgTypes,
	}.Build()
	File_proto_crypto_parser_proto = out.File
	file_proto_crypto_parser_proto_goTypes = nil
	file_proto_crypto_parser_proto_depIdxs = nil
}
